---
- name: Ensure the scripts directory exists
  file:
    path: "/home/{{ remote_user }}/var/scripts"
    state: directory
    mode: '0755'

- name: Ensure the logs directory exists
  file:
    path: "/home/{{ remote_user }}/var/log"
    state: directory
    mode: '0755'

- name: Ensure the log file exists
  copy:
    content: ""
    dest: "/home/{{ remote_user }}/var/log/monitor.log"
    mode: '0644'

- name: Ensure the test_process_status file exists
  copy:
    content: ""
    dest: "/home/{{ remote_user }}/var/log/test_process_status"
    mode: '0644'

- name: Copy test_monitor script
  template:
    src: templates/test_monitor.sh.j2
    dest: /home/{{ remote_user }}/var/scripts/test_monitor.sh
    mode: '0755'

- name: Deploy the systemd unit
  template:
    src: templates/test_monitor.service.j2
    dest: "/etc/systemd/system/test_monitor.service"
    mode: '0644'

- name: Deploy the systemd timer
  template:
    src: files/test_monitor.timer
    dest: "/etc/systemd/system/test_monitor.timer"
    mode: '0644'

- name: Reload systemd to apply changes
  command: systemctl daemon-reload

- name: Enable and start the timer
  systemd:
    name: test_monitor.timer
    enabled: yes
    state: started

- name: Check status of monitor_test.service
  command: sudo systemctl status test_monitor.service
  register: test_monitor_status

- name: Show the status of test_monitor.timer
  debug:
    msg: "{{ test_monitor_status.stdout }}"